### ISSUE TITLE
How to control it to save mp4?Because it seems to save a mp4 each 10 episode, it save too much

### ISSUE THREAD

**Issue by whisperLiang** [Ryan-Rudes/colabgymrender#1]

**Comment by ryanrudes** [comment]
Use the `pause` and `resume` functions. They pause and resume both frame recording and saving. If you'd like to skip certain episodes, you can for example pause the recording for 9 episodes, then let it record for one. In the future, I'll add the ability to design a custom recording schedule so that these things won't be so manual.
